;############################################################################################################################
; Use to build all and the output is send to the build.txt file.
; pio run >build.txt 
;
; The buildfs will build the littlefs from the data_dir
; pio run -t buildfs 
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; https://github.com/pioarduino/platform-espressif32
;
;############################################################################################################################
[platformio]
src_dir = ./src
data_dir = ./Littlefs

[env]
framework = arduino
lib_deps = 
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/ESPAsyncTCP.git
    https://github.com/tzapu/WiFiManager.git
	bblanchon/ArduinoJson
    arduino-libraries/NTPClient

build_flags =
    -DCORE_DEBUG_LEVEL=2
    -DCONFIG_ASYNC_TCP_MAX_ACK_TIME=5000   ;// (keep default 5000)
    -DCONFIG_ASYNC_TCP_PRIORITY=10         ;// (keep default 10 )
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=64       ;// (keep default 65)
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1      ;// force async_tcp task to be on same core as Arduino app (default is any core)
    -DCONFIG_ASYNC_TCP_STACK_SIZE=16384    ;// reduce the stack size (default is 16K)
lib_compat_mode = strict
lib_ldf_mode = chain
extra_scripts = Scripts/extra_script.py
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
; satble version  3.3.7 version @ 2026-03 
platform32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

[env:esp32dev_4MB]
platform = ${env.platform32} 
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}

board = esp32dev
board_build.partitions = partitions/no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32dev_8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
board = esp32dev
board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32dev_16MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
board = esp32dev
board_build.partitions = partitions/no_ota_large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32dev_32MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

board = esp32dev
board_build.partitions = partitions/no_ota_large_spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432

;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

; WEMOS LOLIN S2 PICO
[env:lolin_s2_pico_4MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
 ;   -D ARDUINO_USB_MODE=1
 ;   -D ARDUINO_USB_CDC_ON_BOOT=1

board = lolin_s2_pico
board_build.partitions = partitions/no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:lolin_s2_pico_8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1

board = lolin_s2_pico
board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:lolin_s2_pico_16MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1

board = lolin_s2_pico
board_build.partitions = partitions/no_ota_large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-s3-devkitc-1-4MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

board = esp32-s3-devkitc-1
board_build.partitions = partitions/no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14


[env:esp32-s3-devkitc-1-Debug]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-s3-devkitc-1
debug_tool = esp-builtin
debug_build_flags = -g3 -O0
debug_init_break = tbreak setup
; debug_port = 
board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local 

[env:esp32-s3-devkitc-1-8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1

board = esp32-s3-devkitc-1
board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=192.168.5.33 ;ESPRedCanary.local 

[env:esp32-s3-devkitc-1-16MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1

board = esp32-s3-devkitc-1
board_build.partitions = partitions/no_ota_large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-s3-devkitc-1-32MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1

board = esp32-s3-devkitc-1
board_build.partitions = partitions/no_ota_large_spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c3-devkitc-02-4MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions/no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c3-devkitc-02-8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c3-devkitc-02-16MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions/no_ota_large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c3-devkitc-02-32MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions/no_ota_large_spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c5-devkitc-1-4MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c5-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c5-devkitc-1-8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c5-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESP-ESPRedCanary.local ;192.168.5.14

[env:esp32-c5-devkitc-1-16MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c5-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c5-devkitc-1-32MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c5-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c6-devkitc-1-4MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c6-devkitc-1-8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESP-ESPRedCanary.local ;192.168.5.14

[env:esp32-c6-devkitc-1-16MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c6-devkitc-1-32MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions/no_ota_large_spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

[env:esp32-c61-devkitc1-n8r2-8MB]
platform = ${env.platform32}
lib_deps =
    ${env.lib_deps}

build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c61-devkitc1-n8r2

board_build.partitions = partitions/no_ota_large_spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="RedCanary"
;upload_protocol = espota
;upload_port=ESPRedCanary.local ;192.168.5.14

